### ISSUE TITLE
PowerShell Core 6.0 GA Compatibility

### ISSUE THREAD

**Issue by jmppwsh-zz** [raandree/NTFSSecurity#26]
Curious if this is fully compatible with PS Core as it uses several other libraries instead of the .NET Framework libraries to get done what it is doing :).  If it is fully compatible, it's probably worth noting that explicitly, and tagging it appropriately on PS Gallery.

Thank you for the useful module!

**Comment by timoline** [comment]
Same question here...

**Comment by timoline** [comment]
I did a few tests on pswh 6.0.1, and it lookslike its working fine

**Comment by raandree** [comment]
Sorry for the late reply. I have never tested this module on pswh 6. @nyanhp indicated that in #29 that AlphaFS is not compatible with .net Core. So I am wondering why this module works just out of the box in pswh 6.

**Comment by nyanhp** [comment]
It seems to work, but I cannot say why. Our project is compiled against .NET Full. I can only assume that it works on a Windows system with the full .NET framework installed. Technically however it is not compatible with Core and should not work.
In my opinion, we cannot say we are compatible with core if we cannot reliably answer this for the modules/libraries that we require like AlphaFS. The .NET projects are definitely not compatible. Compiling them against .NET standard creates multiple issues I was unable to resolve.

It definitely does not work if your only installed .NET framework is Core. On Linux, the module cannot be imported since we rely on System.Windows.Forms somewhere in the code (to name the first of probably many exceptions).

For our intents and purposes, managing NTFS ACLs on Windows operating systems, it probably works.

**Comment by raandree** [comment]
Quite some time ago but I have now managed to do some tests with NTFSSecurity on PowerShell 6. I have identified some compatibility issues but nothing big. A version that runs on PowerShell 6 will be release quite soon.

**Comment by PSVortex** [comment]
Absolutely fantastic news!

**Comment by SirWobbyTheFirst** [comment]
Hi Raandree,

Any updates on this the last response was from November 30th and I'm looking to convert over to PSCore.

Thanks

**Comment by sql-sith** [comment]
For those who say that this works with PS Core 6 with "some compatibility issues but nothing big" (@raandree) or that it looks like it's "working fine" (@timoline) ... HALP! I cannot get NTFSSecurity to even import in PS Core 6. I get this error:
```
Import-Module : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```
If I try to use `[System.Reflection.Assembly]::LoadWithPartialName` or fancier scripts that use something like `[System.Assembly]::Load`, I get this error:
```
Exception calling "LoadWithPartialName" with "1" argument(s): "Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. Operation is not supported. (Exception from HRESULT: 0x80131515)"
```
So how are you even able to test this? I am on Windows 10 1903 and Powershell 6.2.1 Core, if it matters.

Thanks!

**Comment by raandree** [comment]
Finished, releasing 4.2.5 today with PowerShell core support.
