### ISSUE TITLE
Problem of Installation

### ISSUE THREAD

**Issue by christophe-lechenadec** [raandree/NTFSSecurity#9]
I do not manage To install the module,
Which files exactly must be placed in the NTFSSecurity Folder.
 - All Files and Folders in Zip ?
==> get-module -ListAvailable
OK
==> Import-Module NTFSSecurity
Import-Module : Le module «NTFSSecurity» spécifié n'a pas été chargé, car aucun fichier de module valide n'a été
trouvé dans un répertoire de module.
Au caractère Ligne:1 : 1
+ Import-Module NTFSSecurity
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (NTFSSecurity:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

If I place all the files of the under-folder Zip/NTFSSecurity only
==> get-module -ListAvailable
OK
==> Import-Module NTFSSecurity
error missing DLL files.

**Comment by maxferrario-msf** [comment]
Same error here: windows 7, powershell v5

**Comment by joshuamhanley** [comment]
You both probably need to click Releases on the project page and download
the release instead of the whole project, which is the uncompiled source
code. Make sure you Unblock (right click, properties, uncheck the check
box) the .zip before extracting the module folder and dropping it in your
$env:PSModulePath.

I struggled with this too, but it's kind of Github's fault for not making
Releases more obvious, combined with the fact that most PS modules on the
site are just PS code, so grabbing the whole project works for those and
builds a bad habit.

On Jan 20, 2017 5:45 AM, "maxferrario-msf" <notifications@github.com> wrote:

Same error here: windows 7, powershell v5

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/raandree/NTFSSecurity/issues/9#issuecomment-274042191>,
or mute the thread

**Comment by raandree** [comment]
Right, please do not download the code but the latest release. Alternatively, you can get the module from the PowerShell Gallery (Install-Module -Name NTFSSecurity).

I have installed myself a Windows 7 machine with PowerShell 5 and could not reproduce any problem loading the module. For deploying the machine I have used the script [03 PowerShell 5 on Windows 7.ps1](https://github.com/AutomatedLab/AutomatedLab/blob/develop/SampleScripts/Introduction/03%20PowerShell%205%20on%20Windows%207.ps1), which did the job in less than 15 minutes.

**Comment by maxferrario-msf** [comment]
Thanks for the clarification guys: I downloaded and installed the release and it's working as expected.
